### ISSUE TITLE
WILD ABOUT HEALTH - Error when saving images to products

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#31]
When in the products list and you you try to add an image to a product it give the attach error.

**Comment by elliot-borst-yuranga** [comment]
![error](https://cloud.githubusercontent.com/assets/8906719/6722395/1f3b7742-ce2d-11e4-9efb-bcff74357e3d.png)

**Comment by kenquyen** [comment]
updated long time ago
