### ISSUE TITLE
WILD ABOUT HEALTH - Linking products to Specials isnt working

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#33]
http://wildabouthealth.com.au/

On the home page, scroll down, there are feature products

If you click on a new one that has been added recently eg the bottom two
Alkastream Ultrastream Black & Silv
or 
JC Jojoba 100% Nat Youth Potion 50m

It takes you to a page that says "Sorry product not found"

I Looked in the CMS under ESTORE \ PRODUCTS \ SPECIALS and they appear to have linked it ok.

Can you tell me what the issue is?

**Comment by kenquyen** [comment]
updated on PROD

it is because of the manufacture of the product has not been actived (os_manufacturers.active = NULL), I updated it to 1.
