### ISSUE TITLE
WILD ABOUT HEALTH - metatags not saving

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#34]
Trying to update the meta tags on the site but it doesn’t seem to work.
Example: I’ve created a new page:
http://wildabouthealth.com.au/section.content/illawarra
 
I added the metas in the admin area.
Saved and it said that it’s saved successfully but when going back to the page – the metas are gone
Checked the live page and metas are not there.

**Comment by kenquyen** [comment]
updated on PROD
