### ISSUE TITLE
DGB LAW - Insert Tracking Code to website

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#39]
How to start using the Capture Code.

1.   Copy the code below.

2.   Add the code to a global header file on your website. If possible, insert the capture code to right before the end head tag <head>.  If you have a static HTML site, make sure it is included on every HTML page.

**Comment by elliot-borst-yuranga** [comment]
[CODE.txt | uploaded via ZenHub](https://files.zenhub.io/558a0881d52a48bd1e18d68a)

**Comment by pankaj-lehar** [comment]
Hello Elliot,

This is done. Please check and confirm.

Thanks
