### ISSUE TITLE
WILD ABOUT HEALTH - Cant upload image to blog

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#40]
When trying to add an mage to a blog post, clicking send to server does nothing.

CMS \ Module \ Blogs

Add a new blog

Click the add image button

Go to the upload tabe, browse for an image then click send to server.

Nothing happens.

**Comment by pankaj-lehar** [comment]
Hello Elliot,

I test this feature that is working fine from my side. you can check there i post the two blog posts that in inactive mode.

Please check and confirm.

Thanks

**Comment by elliot-borst-yuranga** [comment]
Ive tried again in Chrome, Firefox and Internet Explorer 11, it doesnt work for me.

I cant use the upload tab, and I cant use the "Image Info" tab and browse the server and then upload from there, it shows nothing.

Please contact me as early as possible to discuss this.

**Comment by elliot-borst-yuranga** [comment]
Please force https for the cms
Please fix the broswe button in internet explorer

**Comment by pankaj-lehar** [comment]
Hello Elliot,

I solved the blog image issue. I mean force the cms http to https. Please check and confirm.

IE issue is solve later.

If there are any issue Please let me know.

Thanks

**Comment by pankaj-lehar** [comment]
Hello Elliot,

There are also done the IE Issue. Please check and confirm.

Thanks

**Comment by elliot-borst-yuranga** [comment]
Yep IE is working for me, closing this one off
