### ISSUE TITLE
WILD ABOUT HEALTH - Order emails not coming through

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#41]
The client has told me that order emails are not coming through.

Can you please take a look at this, also in the CMS parameters there is admin_email, is this related to orders?

**Comment by pankaj-lehar** [comment]
HI Elliot,

I had check this and there are two mails going from the website. one to the customer and another to the seller. but there is no code written for sending mail to admin. 

Please let me know shall we add code to send mail to admin.

Thanks

**Comment by elliot-borst-yuranga** [comment]
![image](https://cloud.githubusercontent.com/assets/8906719/8840953/47b661bc-312b-11e5-9d97-3cbfacbf54af.png)

The seller is wecanhelp@wildabouthealth.com.au

Are you saying an email is going to that?

**Comment by elliot-borst-yuranga** [comment]
Ok I found the issue, MX DNS problem, its fixed.

Closing this ticket.
