### ISSUE TITLE
WILD ABOUT HEALTH - Change Default Ordering on Orders Screen

### ISSUE THREAD

**Issue by elliot-borst-yuranga** [yurangaAU/YurangaIssues#42]
In the CMS \ ESTORE \ Order

The default ordering seems to be Date Purchased, oldest to newest, can you please reverse that so that the newest order is always at the top.

**Comment by pankaj-lehar** [comment]
Hello Elliot,

This is done.Please check and confirm.

Thanks

**Comment by elliot-borst-yuranga** [comment]
Awesome thanks
